const meta = {
  Genesis: {
    chapters: 50,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Exodus: {
    chapters: 40,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Leviticus: {
    chapters: 27,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Numbers: {
    chapters: 36,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Deuteronomy: {
    chapters: 34,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Josha: {
    chapters: 24,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Judges: {
    chapters: 21,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Ruth: {
    chapters: 4,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  ISamuel: {
    chapters: 31,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IISamuel: {
    chapters: 24,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IKings: {
    chapters: 22,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IIKings: {
    chapters: 25,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IChronicles: {
    chapters: 29,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IIChronicles: {
    chapters: 36,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Ezra: {
    chapters: 10,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Nehemiah: {
    chapters: 13,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Esther: {
    chapters: 10,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Job: {
    chapters: 42,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Psalms: {
    chapters: 150,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Proverbs: {
    chapters: 31,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Ecclesiastes: {
    chapters: 12,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  songOfSolomon: {
    chapters: 8,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Isaiah: {
    chapters: 66,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Jeremiah: {
    chapters: 52,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Lamentations: {
    chapters: 5,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Ezekiel: {
    chapters: 48,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Daniel: {
    chapters: 12,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Hosea: {
    chapters: 14,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Joel: {
    chapters: 3,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Amos: {
    chapters: 9,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Obadiah: {
    chapters: 1,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Jonah: {
    chapters: 4,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Micah: {
    chapters: 7,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Nahum: {
    chapters: 3,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Habakkuk: {
    chapters: 3,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Zephaniah: {
    chapters: 3,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Haggai: {
    chapters: 2,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Zechariah: {
    chapters: 14,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Malachi: {
    chapters: 4,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Matthew: {
    chapters: 28,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Mark: {
    chapters: 16,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Luke: {
    chapters: 24,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  John: {
    chapters: 21,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Acts: {
    chapters: 28,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Romans: {
    chapters: 16,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IChorinthians: {
    chapters: 16,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IIChorinthians: {
    chapters: 13,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Galatians: {
    chapters: 6,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Ephesians: {
    chapters: 6,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Philippians: {
    chapters: 4,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Colossians: {
    chapters: 4,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IThesselonians: {
    chapters: 5,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IIThesselonians: {
    chapters: 3,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  ITimothy: {
    chapters: 6,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IITimothy: {
    chapters: 4,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Titus: {
    chapters: 3,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Phelemon: {
    chapters: 1,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Hebrews: {
    chapters: 13,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  James: {
    chapters: 5,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IPeter: {
    chapters: 5,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IIPeter: {
    chapters: 5,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IJohn: {
    chapters: 5,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IIJohn: {
    chapters: 1,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  IIIJohn: {
    chapters: 1,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Jude: {
    chapters: 1,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
  Revelation: {
    chapters: 22,
    "ta-irvtam": "Tamil",
    "en-kjv": "English(KJV)",
    "sa-Mlym-IN-laukika-sanml": "Malayalam",
    "hi-IN-irvhin": "Hindi",
    "sa-Telu-IN-laukika-sante": "Telugu",
    "sa-Knda-IN-laukika-sanka": "Kannada",
  },
};
